"""add build_quality table

Revision ID: 212f51617bb3
Revises: 44a7db9b0e39
Create Date: 2026-06-08 14:45:55.585787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212f51617bb3'
down_revision: Union[str, Sequence[str], None] = '44a7db9b0e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('q_score', sa.Float(), nullable=True),
    sa.Column('score_body_construction', sa.Float(), nullable=True),
    sa.Column('score_nvh_isolation', sa.Float(), nullable=True),
    sa.Column('score_interior_materials', sa.Float(), nullable=True),
    sa.Column('score_paint_corrosion', sa.Float(), nullable=True),
    sa.Column('score_electrical_aging', sa.Float(), nullable=True),
    sa.Column('score_cosmetic_aging', sa.Float(), nullable=True),
    sa.Column('body_construction_notes', sa.Text(), nullable=True),
    sa.Column('nvh_isolation_notes', sa.Text(), nullable=True),
    sa.Column('interior_materials_notes', sa.Text(), nullable=True),
    sa.Column('paint_corrosion_notes', sa.Text(), nullable=True),
    sa.Column('electrical_aging_notes', sa.Text(), nullable=True),
    sa.Column('cosmetic_aging_notes', sa.Text(), nullable=True),
    sa.Column('q_score_notes', sa.Text(), nullable=True),
    sa.Column('platform_type', sa.String(length=50), nullable=True),
    sa.Column('assembly_plant', sa.String(length=100), nullable=True),
    sa.Column('weld_technology', sa.String(length=50), nullable=True),
    sa.Column('panel_gap_mm', sa.Float(), nullable=True),
    sa.Column('engine_mount_type', sa.String(length=50), nullable=True),
    sa.Column('glass_type', sa.String(length=100), nullable=True),
    sa.Column('leather_grade', sa.String(length=50), nullable=True),
    sa.Column('wood_type', sa.String(length=50), nullable=True),
    sa.Column('paint_stages', sa.Integer(), nullable=True),
    sa.Column('sound_deadening_rating', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.drop_column('performance', 'unlimited_top_speed_mph')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('unlimited_top_speed_mph', sa.REAL(), nullable=True))
    op.drop_table('build_quality')
    # ### end Alembic commands ###
