"""add dimensional reliability scores

Revision ID: 44a7db9b0e39
Revises: f041816d9358
Create Date: 2026-06-08 11:58:27.428596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a7db9b0e39'
down_revision: Union[str, Sequence[str], None] = 'f041816d9358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reliability', sa.Column('score_engine', sa.Float(), nullable=True))
    op.add_column('reliability', sa.Column('score_transmission', sa.Float(), nullable=True))
    op.add_column('reliability', sa.Column('score_chassis', sa.Float(), nullable=True))
    op.add_column('reliability', sa.Column('score_electronics', sa.Float(), nullable=True))
    op.add_column('reliability', sa.Column('score_ease_of_repair', sa.Float(), nullable=True))
    op.add_column('reliability', sa.Column('score_notes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reliability', 'score_notes')
    op.drop_column('reliability', 'score_ease_of_repair')
    op.drop_column('reliability', 'score_electronics')
    op.drop_column('reliability', 'score_chassis')
    op.drop_column('reliability', 'score_transmission')
    op.drop_column('reliability', 'score_engine')
    # ### end Alembic commands ###
    op.add_column('performance', sa.Column('unlimited_top_speed_mph', sa.REAL(), nullable=True))
