"""add agentic ingestion tables + powertrain_ice and market_history fields

Revision ID: cbfd705cc91b
Revises: 
Create Date: 2026-05-30 12:47:29.645399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfd705cc91b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('source_site', sa.String(length=100), nullable=True),
    sa.Column('rating_overall', sa.Float(), nullable=True),
    sa.Column('rating_reliability', sa.Float(), nullable=True),
    sa.Column('rating_performance', sa.Float(), nullable=True),
    sa.Column('rating_comfort', sa.Float(), nullable=True),
    sa.Column('rating_value', sa.Float(), nullable=True),
    sa.Column('review_excerpt', sa.Text(), nullable=True),
    sa.Column('review_url', sa.String(length=500), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('wheelbase_mm', sa.Integer(), nullable=True),
    sa.Column('track_front_mm', sa.Integer(), nullable=True),
    sa.Column('track_rear_mm', sa.Integer(), nullable=True),
    sa.Column('front_overhang_mm', sa.Integer(), nullable=True),
    sa.Column('rear_overhang_mm', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.create_table('ingest_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('raw_paste', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_site', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('gaps_and_questions', sa.JSON(), nullable=True),
    sa.Column('agent_messages', sa.JSON(), nullable=True),
    sa.Column('final_car_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source_site', sa.String(length=100), nullable=True),
    sa.Column('test_date', sa.DateTime(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zeperfs_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('zeperfs_index', sa.Float(), nullable=True),
    sa.Column('sportivity_index', sa.Float(), nullable=True),
    sa.Column('perfs_prix_ratio', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('recorded_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.add_column('market_history', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('market_history', sa.Column('price_eur', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('power_kw', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('specific_power_per_cylinder_w_cm2', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('bmep_bar', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('mean_piston_speed_m_s', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('engine_torque_nm', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('fuel_consumption_mixed_l_100km', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('fuel_consumption_sport_l_100km', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('co2_emissions_g_km', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('fuel_tank_capacity_l', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('reserve_fuel_l', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('top_speed_claimed_kmh', sa.Float(), nullable=True))
    op.add_column('powertrain_ice', sa.Column('power_reserve_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('powertrain_ice', 'power_reserve_pct')
    op.drop_column('powertrain_ice', 'top_speed_claimed_kmh')
    op.drop_column('powertrain_ice', 'reserve_fuel_l')
    op.drop_column('powertrain_ice', 'fuel_tank_capacity_l')
    op.drop_column('powertrain_ice', 'co2_emissions_g_km')
    op.drop_column('powertrain_ice', 'fuel_consumption_sport_l_100km')
    op.drop_column('powertrain_ice', 'fuel_consumption_mixed_l_100km')
    op.drop_column('powertrain_ice', 'engine_torque_nm')
    op.drop_column('powertrain_ice', 'mean_piston_speed_m_s')
    op.drop_column('powertrain_ice', 'bmep_bar')
    op.drop_column('powertrain_ice', 'specific_power_per_cylinder_w_cm2')
    op.drop_column('powertrain_ice', 'power_kw')
    op.drop_column('market_history', 'price_eur')
    op.drop_column('market_history', 'currency')
    op.drop_table('zeperfs_indices')
    op.drop_table('performance_measurements')
    op.drop_table('ingest_sessions')
    op.drop_table('dimensions')
    op.drop_table('car_reviews')
    # ### end Alembic commands ###
