"""add family and variant fields to cars

Revision ID: f041816d9358
Revises: 7ea185577375
Create Date: 2026-05-30 14:54:05.699065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f041816d9358'
down_revision: Union[str, Sequence[str], None] = '7ea185577375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('family', sa.String(length=100), nullable=True))
    op.add_column('cars', sa.Column('variant', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'variant')
    op.drop_column('cars', 'family')
    # ### end Alembic commands ###
