-- Backfill reliability dimension scores for 32 cars
-- Generated by backfill_calc.py
-- DO NOT modify reliability_score (total) - only adding dimension scores

UPDATE reliability SET
    score_engine = 80,
    score_transmission = 82,
    score_chassis = 78,
    score_electronics = 65,
    score_ease_of_repair = 65,
    common_failures = '{"PCV valve failure (under supercharger)": 3, "Water pump/thermostat housing": 3, "Timing chain tensioner (5-10%)": 3, "Supercharger wear": 2, "Carbon buildup (intake valves)": 2}',
    known_issues = '{"EA837 (CAJA/CREC)": "One of Audis most reliable modern engines. Risk score 4.0/10 per Autoscore. Facelift 2015+ improved with dual injection + decoupling clutch.", "Timing chain": "At BACK of engine = engine removal for service. Startup rattle >3 seconds warrants inspection. Many 200k+ without chain service.", "ZF 8HP": "One of the best automatics. No mechatronic issues unlike DL382. Fluid change at 40-60k."}'
WHERE car_id = 155;

UPDATE reliability SET
    score_engine = 80,
    score_transmission = 72,
    score_chassis = 82,
    score_electronics = 72,
    score_ease_of_repair = 69,
    common_failures = '{"Oil consumption": 3, "DL382+ mechatronic (S-tronic)": 3, "Water pump/thermostat": 2, "Timing chain tensioner wear": 2, "Early rocker arm (2018-early 2019)": 2}',
    known_issues = '{"EA839 (DLZA)": "Shared with Porsche Macan S, VW Touareg. Generally reliable but oil consumption most reported. NA spec deletes port injector = carbon buildup risk.", "DL382+ S-tronic": "Mechatronic is weak point. Harsh low-speed shifts. P0718, P179F codes. $2-3K mechatronic.", "Cd 0.23": "Best drag coefficient of any combustion Audi."}'
WHERE car_id = 32;

UPDATE reliability SET
    score_engine = 70,
    score_transmission = 82,
    score_chassis = 62,
    score_electronics = 75,
    score_ease_of_repair = 67,
    common_failures = '{"VANOS failure": 4, "subframe cracks": 3, "rod bearings": 3, "rear subframe bushings": 2}',
    known_issues = '{"VANOS codes": "Inspect at 80k mi. S54 VANOS rebuild $2-3K.", "subframe plate cracking": "Race cars mostly. Weld-in reinforcement plates available.", "rod bearings": "BMW recall/extended warranty. Replace with BE bearings preventatively."}'
WHERE car_id = 3;

UPDATE reliability SET
    score_engine = 58,
    score_transmission = 78,
    score_chassis = 62,
    score_electronics = 58,
    score_ease_of_repair = 50,
    common_failures = '{"timing belt tensioner": 4, "water pump": 3, "valve guides": 3, "exhaust manifold cracks": 2}',
    known_issues = '{"timing belt tensioner failure": "Replace at 15k mi or 5 years. Engine-out service $5-10K.", "water pump": "Replace with metal OEM impeller.", "valve guides": "Exhaust valve guides wear prematurely. Full rebuild indicator."}'
WHERE car_id = 5;

UPDATE reliability SET
    score_engine = 83,
    score_transmission = 86,
    score_chassis = 72,
    score_electronics = 76,
    score_ease_of_repair = 67,
    common_failures = '{"clutch fan": 2, "hardtop recall": 1, "AP1 rear suspension twitchiness": 2}',
    known_issues = '{"clutch fan": "Replace at 50k mi preventatively.", "AP1 suspension": "Aggressive rear geometry causes snap oversteer. AP2 geometry retrofit common.", "F20C": "Largest displacement per liter of any production car at 120 hp/L. Robust."}'
WHERE car_id = 6;

UPDATE reliability SET
    score_engine = 80,
    score_transmission = 85,
    score_chassis = 78,
    score_electronics = 72,
    score_ease_of_repair = 81,
    common_failures = '{"Carbon buildup (GDI only)": 3, "Turbo oil line leaks": 2, "Brake rotor warpage": 2}',
    known_issues = '{"Lambda II 3.3T": "Same as G70 3.3T. GDI-only = carbon buildup at 40-60k. Proven V6.", "Stinger GT": "Brembo brakes standard. Larger aftermarket than G70. 10yr/100k warranty.", "Discontinued 2024": "Values may hold as only Kia liftback GT."}'
WHERE car_id = 33;

UPDATE reliability SET
    score_engine = 75,
    score_transmission = 78,
    score_chassis = 62,
    score_electronics = 30,
    score_ease_of_repair = 32,
    common_failures = '{"ABC suspension": 5, "SBC brakes": 4, "roof hydraulics": 3}',
    known_issues = '{"ABC": "Active Body Control hydraulic suspension is THE known issue. Struts, lines, pump \u2014 $5-10K+ when it fails.", "SBC": "Sensotronic Brake Control pump fails and has a 10-year/service life counter. MB extended warranty on this.", "intercooler pump": "Supercharger intercooler coolant pump fails \u2014 cheap part, causes heat soak."}'
WHERE car_id = 141;

UPDATE reliability SET
    score_engine = 72,
    score_transmission = 78,
    score_chassis = 68,
    score_electronics = 42,
    score_ease_of_repair = 47,
    common_failures = '{"turbo wastegate rattle": 3, "ABC suspension": 3, "oil consumption": 2}',
    known_issues = '{"wastegate": "M157 turbo wastegate rattle under deceleration. AMG extended warranty on turbos.", "ABC": "Same ABC issues as R230 but somewhat improved.", "battery": "Multiple battery drain issues if not driven regularly."}'
WHERE car_id = 142;

UPDATE reliability SET
    score_engine = 78,
    score_transmission = 80,
    score_chassis = 72,
    score_electronics = 62,
    score_ease_of_repair = 52,
    common_failures = '{"48V system glitches": 2, "MBUX infotainment": 2, "rear axle steering sensor": 1}',
    known_issues = '{"48V": "Early 2022 models had 48V electrical system glitches \u2014 resolved via software updates.", "MBUX": "Infotainment system occasional reboots, OTA updates fix most issues.", "warranty": "Most cars still under factory warranty through 2026."}'
WHERE car_id = 143;

UPDATE reliability SET
    score_engine = 80,
    score_transmission = 80,
    score_chassis = 62,
    score_electronics = 72,
    score_ease_of_repair = 59,
    common_failures = '{"fuel injection pump": 4, "drum brakes": 2}',
    known_issues = '{"fuel injection pump": "Bosch mechanical DI pump requires specialist rebuild.", "brakes": "Drum brakes all around \u2014 period correct but weak by modern standards."}'
WHERE car_id = 135;

UPDATE reliability SET
    score_engine = 75,
    score_transmission = 75,
    score_chassis = 58,
    score_electronics = 72,
    score_ease_of_repair = 65,
    common_failures = '{"Solex carburetors": 3, "drum brakes": 2}',
    known_issues = '{"carburetors": "Twin Solex 44PHH need periodic rebuild and sync.", "drum brakes": "All drums \u2014 adequate for cruising, not for spirited driving."}'
WHERE car_id = 136;

UPDATE reliability SET
    score_engine = 85,
    score_transmission = 82,
    score_chassis = 78,
    score_electronics = 72,
    score_ease_of_repair = 89,
    common_failures = '{"fuel injection pump": 3, "swing axle": 2}',
    known_issues = '{"injection pump": "Bosch mechanical injection pump needs calibration every 30k mi.", "swing axle": "Rear swing axle can cause tuck-under if driven hard."}'
WHERE car_id = 137;

UPDATE reliability SET
    score_engine = 82,
    score_transmission = 82,
    score_chassis = 78,
    score_electronics = 58,
    score_ease_of_repair = 93,
    common_failures = '{"timing chain guides": 3, "AC system": 3}',
    known_issues = '{"timing chain": "Inspect/replace guides at 100k mi.", "AC": "R12 to R134a conversion needed. Compressor seal leaks common."}'
WHERE car_id = 138;

UPDATE reliability SET
    score_engine = 82,
    score_transmission = 82,
    score_chassis = 80,
    score_electronics = 55,
    score_ease_of_repair = 69,
    common_failures = '{"brake vacuum booster": 3, "level regulation": 3}',
    known_issues = '{"brake booster cracking": "Common on high-mile W124s.", "500E specific": "Hand-assembled by Porsche at Zuffenhausen. Wider fenders, different suspension.", "parts cost": "Porsche-built means some unique parts with MB tax + Porsche tax."}'
WHERE car_id = 7;

UPDATE reliability SET
    score_engine = 82,
    score_transmission = 82,
    score_chassis = 78,
    score_electronics = 48,
    score_ease_of_repair = 78,
    common_failures = '{"biodegradable wiring harness": 4, "soft top hydraulics": 3}',
    known_issues = '{"wiring harness": "Pre-1996 cars have biodegradable insulation that crumbles. Full harness replacement $2-4K.", "soft top": "Hydraulic cylinder seals leak over time. $800-1500 per cylinder."}'
WHERE car_id = 139;

UPDATE reliability SET
    score_engine = 68,
    score_transmission = 75,
    score_chassis = 72,
    score_electronics = 35,
    score_ease_of_repair = 81,
    common_failures = '{"dual coil packs": 4, "ADS suspension": 4, "wiring harness": 4}',
    known_issues = '{"coil packs": "Two coil packs, ~$600-1200 each. 24 spark plugs to replace.", "ADS": "Active hydraulic suspension \u2014 accumulator spheres and valve blocks fail. Very expensive.", "coolant hoses": "13+ engine coolant hoses, many buried deep. Preventative replacement recommended."}'
WHERE car_id = 140;

UPDATE reliability SET
    score_engine = 58,
    score_transmission = 72,
    score_chassis = 72,
    score_electronics = 55,
    score_ease_of_repair = 52,
    common_failures = '{"M272 balance shaft wear": 4, "M271 balance shaft gear": 3, "7G-Tronic mechatronic sleeve": 3, "valve cover gasket leak (M272)": 3, "MAF sensor": 2, "thermostat": 2}',
    known_issues = '{"M272 balance shaft": "Well-documented 2004-2008 design flaw; mileage-dependent. Engine out job.", "7G-Tronic 722.9 mechatronic": "Sleeve/conductor plate wears, replaced with updated unit.", "valve cover leak (M272)": "Plastic covers warp with heat; replace with aluminum OE."}'
WHERE car_id = 144;

UPDATE reliability SET
    score_engine = 62,
    score_transmission = 75,
    score_chassis = 72,
    score_electronics = 55,
    score_ease_of_repair = 58,
    common_failures = '{"M272 balance shaft wear": 4, "7G-Tronic mechatronic sleeve": 3, "lower control arm bushings": 3, "sunroof track/electrical": 2, "transfer case (4MATIC)": 2, "PCV system": 2}',
    known_issues = '{"M272 balance shaft": "Same design flaw as W204; engine-out to fix.", "lower control arms": "80-100K mile wear; cheap to replace ($300-500 corners).", "sunroof": "Track and drain tube issues \u2014 early 2008-2011 cars."}'
WHERE car_id = 146;

UPDATE reliability SET
    score_engine = 80,
    score_transmission = 82,
    score_chassis = 80,
    score_electronics = 72,
    score_ease_of_repair = 93,
    common_failures = '{"M274 balance shaft wear (early)": 2, "AIRMATIC air spring": 3, "9G-Tronic conductor plate": 2, "MBUX/comand glitches": 1, "TPMS sensor": 1}',
    known_issues = '{"M274 balance shaft": "2015-2016 cars; later engines revised. 80-120K mile onset.", "AIRMATIC": "Air springs and struts are $1.5-2.5K per corner; many owners bypass with coil spring conversion.", "9G-Tronic 725.0": "Far more reliable than the 722.9 it replaced."}'
WHERE car_id = 145;

UPDATE reliability SET
    score_engine = 62,
    score_transmission = 72,
    score_chassis = 68,
    score_electronics = 38,
    score_ease_of_repair = 38,
    common_failures = '{"M278 balance shaft gear wear": 4, "M278 valve stem seals (oil consumption)": 3, "DI carbon buildup (intake valves)": 3, "7G-Tronic mechatronic sleeve": 3, "AIRMATIC air spring": 3, "electronic selector module": 2}',
    known_issues = '{"M278 balance shaft": "Same family issue as M272/M276; 80-120K onset. Engine-out job on the V8 is more expensive than the V6 (~$5-7K).", "M278 valve stem seals": "Oil consumption > 1qt/1000mi is a TSB trigger; revised seals 2016+.", "DI carbon buildup": "Walnut blasting intake valves every 80-100K ($800-1200).", "7G-Tronic 722.9": "Mechatronic sleeve at 80-120K; same as every other M272/M276 car."}'
WHERE car_id = 83;

UPDATE reliability SET
    score_engine = 75,
    score_transmission = 78,
    score_chassis = 78,
    score_electronics = 68,
    score_ease_of_repair = 64,
    common_failures = '{"M276 balance shaft wear": 3, "7G-Tronic mechatronic sleeve": 2, "transfer case (4MATIC)": 2, "ignition coil/spark plugs": 2, "PCV system": 2}',
    known_issues = '{"M276 balance shaft": "Milder than M272; engine-out repair if it occurs (80-120K onset).", "7G-Tronic 722.9": "Last-gen 7-speed; mechatronic sleeve wear at 80-120K.", "4MATIC transfer case": "Service every 60K; otherwise robust."}'
WHERE car_id = 147;

UPDATE reliability SET
    score_engine = 80,
    score_transmission = 82,
    score_chassis = 78,
    score_electronics = 70,
    score_ease_of_repair = 76,
    common_failures = '{"M264 balance shaft (early)": 2, "AIRMATIC air spring": 3, "9G-Tronic mechatronic": 2, "48V mild hybrid battery": 2, "MBUX electronics": 1, "EQ Boost ISG": 2}',
    known_issues = '{"M264": "Improved over M274; balance shaft issue largely resolved by 2019.", "48V mild hybrid": "ISG/EQ Boost component failures on 2018-2020 M256 (E450); mostly resolved by 2021.", "AIRMATIC": "Same $1.5-2K per corner exposure as W205."}'
WHERE car_id = 31;

UPDATE reliability SET
    score_engine = 78,
    score_transmission = 82,
    score_chassis = 78,
    score_electronics = 68,
    score_ease_of_repair = 80,
    common_failures = '{"M276 balance shaft wear": 2, "9G-Tronic conductor plate": 2, "AMG sport suspension bushings": 2, "brake pad/rotor wear (sport)": 2, "rear diff mount": 1}',
    known_issues = '{"M276 in C450": "Same M276 as C400 but less stressed; balance shaft failure rare in this tune.", "9G-Tronic 725.0": "Far more reliable than 722.9; conductor plate (~$600 part) the main wear item.", "AMG-specific": "AMG dampers and sport bushings wear faster than non-sport suspension, but no AMG engine or transmission build = no AMG maintenance premium."}'
WHERE car_id = 148;

UPDATE reliability SET
    score_engine = 78,
    score_transmission = 78,
    score_chassis = 78,
    score_electronics = 68,
    score_ease_of_repair = 55,
    common_failures = '{"48V ISG/EQ Boost (early)": 3, "48V battery (early)": 3, "AIRMATIC air spring": 3, "M256 thermostat/coolant pump": 2, "MBUX screen/comand": 1, "fuel injector (early)": 2}',
    known_issues = '{"48V ISG / EQ Boost": "2020-2021 E450s; ISG or 48V lithium battery failure, $2-3K out of warranty. Largely resolved by 2022.", "AIRMATIC": "Same $1.5-2K per corner exposure as W205/W213.", "M256": "Newer engine family; thermostat/coolant pump a minor known issue. Generally robust."}'
WHERE car_id = 149;

UPDATE reliability SET
    score_engine = 68,
    score_transmission = 82,
    score_chassis = 78,
    score_electronics = 58,
    score_ease_of_repair = 50,
    common_failures = '{"IMS bearing": 3, "bore scoring": 2, "RMS leak": 2}',
    known_issues = '{"IMS bearing failure": "Less common on turbo engines but still a risk. Carry spare.", "bore scoring": "Monitor oil temp and consumption. More common on track cars.", "996 Turbo": "Generally more robust than NA 996. M96.70 has reinforced block."}'
WHERE car_id = 2;

UPDATE reliability SET
    score_engine = 92,
    score_transmission = 90,
    score_chassis = 82,
    score_electronics = 78,
    score_ease_of_repair = 92,
    common_failures = '{"boost leaks": 2, "fuel pump": 2}',
    known_issues = '{"2JZ-GTE nearly indestructible": "Check ancillary systems \u2014 fuel pump, boost controller, VVTi solenoid.", "Getrag V160": "Very strong transmission. Dual-mass flywheel can fail at high mileage.", "supra tax": "Parts prices inflated by JDM tax but mechanically excellent."}'
WHERE car_id = 4;

UPDATE reliability SET
    score_engine = 68,
    score_transmission = 78,
    score_chassis = 72,
    score_electronics = 55,
    score_ease_of_repair = 62,
    common_failures = '{"Supercharger clutch failure": 3, "Oil consumption (piston rings)": 3, "Turbo failure (if oil starved)": 2, "Polestar-specific suspension bushings": 2, "Electrical gremlins (CEM)": 1}',
    known_issues = '{"VEA B4204T35 Polestar tune": "Same twincharged architecture as T6 but with aggressive Polestar tune pushing 367 hp. Same SC clutch failure risk, but higher boost = more stress.", "Pre-Geely build quality": "2014-2018 Polestar models built during Volvos transition period. Electronics (CEM module) can be finicky.", "Ohlins": "Ohlins dampers are serviceable but expensive to replace."}'
WHERE car_id = 98;

UPDATE reliability SET
    score_engine = 70,
    score_transmission = 78,
    score_chassis = 72,
    score_electronics = 55,
    score_ease_of_repair = 70,
    common_failures = '{"Supercharger clutch failure": 3, "Oil consumption": 3, "Sensus infotainment": 2, "Air suspension (if equipped)": 3}',
    known_issues = '{"VEA T6 in S90": "Same B4204T27 as S60 T6 but in 4,819 lb flagship. More stress on drivetrain.", "2017-2019": "Early VEA issues \u2014 oil consumption, balancer shaft, timing chain tensioner. 2020+ improved.", "S90 depreciation": "Massive depreciation from $50K+ MSRP. Used 2018-2020 examples $20-35K."}'
WHERE car_id = 160;

UPDATE reliability SET
    score_engine = 80,
    score_transmission = 82,
    score_chassis = 78,
    score_electronics = 72,
    score_ease_of_repair = 75,
    common_failures = '{"Oil consumption (monitor)": 2, "Sensus infotainment glitches": 2, "Body seal leakage": 1, "AC compressor issues": 1}',
    known_issues = '{"VEA T5 B4204T23": "Same reliable turbo-only engine as S60 T5. XC60 is one of the highest-rated luxury compact SUVs.", "Aisin TG-81SC": "Reliable 8-speed. Volvo says sealed for life; Aisin recommends fluid change at 40-50k."}'
WHERE car_id = 158;

UPDATE reliability SET
    score_engine = 72,
    score_transmission = 78,
    score_chassis = 75,
    score_electronics = 62,
    score_ease_of_repair = 70,
    common_failures = '{"Supercharger electromagnetic clutch failure": 3, "Oil consumption": 3, "Turbo failure (if oil starved)": 2, "Premature brake wear": 2}',
    known_issues = '{"VEA T6 in XC60": "Same B4204T27 as S60 T6 but heavier vehicle. More stress on drivetrain. SC clutch is the headline issue.", "T6 discontinued": "T6 discontinued after 2020 (replaced by B6 mild hybrid)."}'
WHERE car_id = 159;

UPDATE reliability SET
    score_engine = 80,
    score_transmission = 82,
    score_chassis = 78,
    score_electronics = 72,
    score_ease_of_repair = 75,
    common_failures = '{"Oil consumption (monitor)": 2, "Sensus infotainment glitches": 2, "Premature front brake wear": 1}',
    known_issues = '{"VEA T5 B4204T26": "Turbo-only = simpler than T6. No supercharger clutch issues. 2019+ SPA engines resolved early piston ring and oil consumption problems. T5 is the reliability sweet spot.", "Aisin TG-81SC": "Reliable 8-speed. Aisin also supplies Toyota."}'
WHERE car_id = 156;

UPDATE reliability SET
    score_engine = 72,
    score_transmission = 78,
    score_chassis = 75,
    score_electronics = 62,
    score_ease_of_repair = 70,
    common_failures = '{"Supercharger electromagnetic clutch failure": 3, "Oil consumption (piston rings)": 3, "Turbo failure (if oil starved)": 2, "Sensus glitches": 2}',
    known_issues = '{"VEA T6 B4204T27": "Twincharged = more failure points. SC electromagnetic clutch is the #1 issue: severe hesitation from stop, often no CEL. $2-3.5K repair.", "2019+ SPA": "Improved over early VEA but SC clutch remains a risk on all T6 years."}'
WHERE car_id = 157;
